name: Metrics
on:
  schedule: [{cron: "0 0 * * *"}]  # every day at midnight
  workflow_dispatch:

jobs:
  github-metrics:
    runs-on: ubuntu-latest
    steps:
      - name: Generate metrics
        uses: lowlighter/metrics@latest
        with:
          token: ${{ secrets.METRICS_TOKEN }}
          user: rassim-medkour
          template: classic
          base: header, activity, repositories
          config_timezone: Africa/Algiers
        
          plugin_languages: yes
          plugin_languages_limit: 8
          plugin_languages_details: bytes-size, percentage
        
          plugin_activity: yes
          plugin_activity_limit: 5
          plugin_activity_days: 14
        
          filename: github-metrics.svg

