name: Metrics
on:
  schedule: [{cron: "0 0 * * *"}]  # every day at midnight
  workflow_dispatch:

jobs:
  github-metrics:
    runs-on: ubuntu-latest
    steps:
      - name: Generate metrics
        uses: lowlighter/metrics@latest
        with:
          token: ${{ secrets.METRICS_TOKEN }}

          user: rassim-medkour
          template: classic
          base: header, activity, community, repositories, metadata
          config_timezone: Africa/Algiers

          # Languages
          plugin_languages: yes
          plugin_languages_ignored: html, css
          plugin_languages_details: bytes-size, percentage
          plugin_languages_limit: 8

          # Activity
          plugin_activity: yes
          plugin_activity_limit: 5
          plugin_activity_days: 14
          plugin_activity_filter: all
          plugin_activity_visibility: all

          # Achievements (nice touch)
          plugin_achievements: yes
          plugin_achievements_threshold: C
          plugin_achievements_secrets: yes
          plugin_achievements_display: detailed

          # Lines of code / timespan
          plugin_lines: yes

          # Notable contributions
          plugin_notable: yes
          plugin_notable_filter: stars
          plugin_notable_repositories: yes

          # Output file
          filename: github-metrics.svg
